### ISSUE TITLE
cannot import name 'segvae' in phiseg_generate_samples.py

### ISSUE THREAD

**Issue by Landwind-Xin** [baumgach/PHiSeg-code#1]
Dear @baumgach,

Thank you very much for sharing such a brilliant project.

I was trying to run  **phiseg_generate_samples.py** to sample from the learned distribution.
Howevery, an error occured as shown below:
```
from phiseg.phiseg_model import segvae
ImportError: cannot import name 'segvae'
```
This error is caused by line 14   **`from phiseg.phiseg_model import segvae`** in phiseg_generate_samples.py.

Also, I have checked, there is no **segvae** in **phiseg_model.py**.

Could you please help me with this?
Many thanks!

**Comment by Landwind-Xin** [comment]
Problem solved.

**Comment by Aditi1894** [comment]
Hi Landwind-Xin,
I am also facing the same issue. Can you please tell me how did you solve the problem?
Thanks in advance.

**Comment by baumgach** [comment]
Hello, there was an issues with same old names being used in the code. While developing the module was called 'segvae' before I refactored it to 'phiseg'. I fixed it now. 

Note that I haven't had time yet to test the evaluation scripts after the refactoring. Let me know if you run into more problems.

**Comment by Aditi1894** [comment]
Yeah Sure. Thanks for the reply.
